org.gradle.caching=true
group=io.ballerina.lib
version=8.7.3-SNAPSHOT

checkstylePluginVersion=10.12.0
spotbugsPluginVersion=6.5.1
shadowJarPluginVersion=9.6.1
downloadPluginVersion=5.4.0
releasePluginVersion=3.1.0
testngVersion=7.6.1
openCsvVersion=5.12.0
ballerinaGradlePluginVersion=4.0.0

ballerinaLangVersion=2201.12.0

jacocoToolVersion=0.8.14
jacksonDatabindVersion=2.18.9
jacksonAnnotationsVersion=2.18.9
jacksonCoreVersion=2.18.9
cometdJavaClientVersion=8.0.11
jettyVersion=12.0.35
gsonVersion=2.10.1
jsonVersion=20240303
slf4jVersion=1.7.36
