[package]
distribution = "2201.11.0-20241117-133400-a3054b77"
org = "ballerinax"
name = "salesforce"
version = "8.4.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Sales & CRM/Customer Relationship Management", "Cost/Freemium", "Vendor/Salesforce", "Area/CRM", "Type/Connector"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-salesforce"

[build-options]
observabilityIncluded = true

[[package.modules]]
name = "salesforce.bulk"
export = true

[[package.modules]]
name = "salesforce.soap"
export = true

[[package.modules]]
name = "salesforce.bulkv2"
export = true

[[package.modules]]
name = "salesforce.apex"
export = true

[[package.modules]]
name = "salesforce.types"
export = true

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
path = "../native/build/libs/salesforce-native-8.4.0.jar"
groupId = "io.ballerinax"
artifactId = "salesforce"
version = "8.4.0"

[[platform.java21.dependency]]
groupId = "com.opencsv"
artifactId = "opencsv"
version = "5.12.0"
path = "./lib/opencsv-5.12.0.jar"

[[platform.java21.dependency]]
groupId = "org.cometd.java"
artifactId = "cometd-java-api-common"
version = "8.0.11"
path = "./lib/cometd-java-api-common-8.0.11.jar"

[[platform.java21.dependency]]
groupId = "org.cometd.java"
artifactId = "cometd-java-api-client"
version = "8.0.11"
path = "./lib/cometd-java-api-client-8.0.11.jar"

[[platform.java21.dependency]]
groupId = "org.cometd.java"
artifactId = "cometd-java-common"
version = "8.0.11"
path = "./lib/cometd-java-common-8.0.11.jar"

[[platform.java21.dependency]]
groupId = "org.cometd.java"
artifactId = "cometd-java-client-common"
version = "8.0.11"
path = "./lib/cometd-java-client-common-8.0.11.jar"

[[platform.java21.dependency]]
groupId = "org.cometd.java"
artifactId = "cometd-java-client-http-common"
version = "8.0.11"
path = "./lib/cometd-java-client-http-common-8.0.11.jar"

[[platform.java21.dependency]]
groupId = "org.cometd.java"
artifactId = "cometd-java-client-http-jetty"
version = "8.0.11"
path = "./lib/cometd-java-client-http-jetty-8.0.11.jar"

[[platform.java21.dependency]]
groupId = "org.eclipse.jetty"
artifactId = "jetty-client"
version = "12.0.31"
path = "./lib/jetty-client-12.0.31.jar"

[[platform.java21.dependency]]
groupId = "org.eclipse.jetty"
artifactId = "jetty-http"
version = "12.0.31"
path = "./lib/jetty-http-12.0.31.jar"

[[platform.java21.dependency]]
groupId = "org.eclipse.jetty"
artifactId = "jetty-io"
version = "12.0.31"
path = "./lib/jetty-io-12.0.31.jar"

[[platform.java21.dependency]]
groupId = "org.eclipse.jetty"
artifactId = "jetty-util"
version = "12.0.31"
path = "./lib/jetty-util-12.0.31.jar"

[[platform.java21.dependency]]
groupId = "org.eclipse.jetty"
artifactId = "jetty-util-ajax"
version = "12.0.31"
path = "./lib/jetty-util-ajax-12.0.31.jar"

[[platform.java21.dependency]]
groupId = "org.json"
artifactId = "json"
version = "20240303"
path = "./lib/json-20240303.jar"

[[platform.java21.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-databind"
version = "2.18.6"
path = "./lib/jackson-databind-2.18.6.jar"

[[platform.java21.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-annotations"
version = "2.18.6"
path = "./lib/jackson-annotations-2.18.6.jar"

[[platform.java21.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-core"
version = "2.18.6"
path = "./lib/jackson-core-2.18.6.jar"
