[package]
org = "salesforce_examples"
name = "distributed_listener"
version = "8.4.0" 
distribution = "2201.11.0"

[[dependency]]
org = "ballerinax"
name = "salesforce"
version = "8.4.0" 
repository = "local"
