[package]
org = "salesforce_examples"
name = "use_soap_api"
version = "8.2.0" 
distribution = "2201.11.0"

[[dependency]]
org = "ballerinax"
name = "salesforce"
version = "8.2.0" 
repository = "local"
