name: GraalVM Check

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17.0.7

      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: latest

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        env:
          packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
          packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
          JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
        run: |
          ./gradlew build -x test

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17.0.7'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check GraalVM installation
        run: |
          echo "GRAALVM_HOME: ${{ env.GRAALVM_HOME }}"
          echo "JAVA_HOME: ${{ env.JAVA_HOME }}"
          native-image --version

      - name: Run Ballerina tests using the native executable
        run: bal test --graalvm ./ballerina
        env:
          JAVA_HOME: /usr/lib/jvm/default-jvm
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          EP_URL: ${{ secrets.EP_URL }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          REFRESH_URL: ${{ secrets.REFRESH_URL }}
