name: Trivy

on:
  workflow_dispatch:
  schedule:
    - cron:  "30 20 * * *"

concurrency:
  # No workflows can run parallel as these are run against the same system
  group: ${{ github.repository }}
  cancel-in-progress: true

jobs:
  call_workflow:
    name: Run Trivy Scan Workflow
    if: ${{ github.repository_owner == 'ballerina-platform' }}
    uses: ballerina-platform/ballerina-library/.github/workflows/trivy-scan-template.yml@main
    secrets: inherit
    with:
      additional-build-flags: "-x :salesforce-examples:build -Pgroups=mock"
